### ISSUE TITLE
monitor id3 performance

### ISSUE THREAD

**Issue by ethannp** [TinyScarletUnicorn/tsu-cogs#19]

**Comment by chasehult** [comment]
id3 has been out for ages, and if we keep this open, this issue will never close.  I'll just do this every now and then.

**Comment by RheingoldRiver** [comment]
the point was for this issue to always be open & pinned and have a bunch of flame graphs attached to it

**Comment by RheingoldRiver** [comment]
that way we can track it over time in 1 place

**Comment by chasehult** [comment]
Sure
